### ISSUE TITLE
Comments in macro definitions

### ISSUE THREAD

**Issue by 8dcc** [Theldus/kat#2]
First of all, great job with the project. I will be using it in [8dcc/c2png](https://github.com/8dcc/c2png).

In the code:

```c
#define MY_MACRO 5 /* Comment */
#define MY_MACRO 5 // Comment
```

The whole line has the same color, including the comments at the end. This is not the case in most editors:

![emacs](https://github.com/Theldus/kat/assets/29655971/6f9787b4-5e78-4f59-b2d2-8c0c2c7cc05d)
![vim](https://github.com/Theldus/kat/assets/29655971/9f4f3072-481c-47af-abf9-fbcb20da506c)

**Comment by Theldus** [comment]
Hi @8dcc,
Thanks for using kat and considering it to your project =).

About your issue... it's a little complicated to add this, since comments can appear in multiple positions within a macro, like:
```c
#define /* hi. */ FOO(x) /* hi. */ ((x)+1 /* hey. */) /* hi. */
```
and it seems that even GitHub's syntax highlighter struggles with this.

So, to correctly highlight a macro is not a trivial task, and unfortunately, I regret to say that I will not add support for it.
